local M = {}

--- Bumped whenever `SCRIPT` changes in a way Neovim depends on. The bridge
--- writes it into `state.json`, so an editor still running last week's script
--- is told to reinstall rather than silently misreporting.
M.VERSION = 1

--- A top-level folder on purpose: it adds no entry to any tracked file, which
--- an embedded package under `Packages/` would.
M.FOLDER = "Assets/NvimBridge"

local EXCLUDES = { M.FOLDER .. "/", M.FOLDER .. ".meta" }

---@param root string
---@return string
function M.dir(root) return root .. "/" .. M.FOLDER .. "/Editor" end

---@param root string
---@return string
function M.watch_dir(root) return root .. "/Library/nvim-unity" end

---@param root string
---@return string
function M.state_file(root) return M.watch_dir(root) .. "/state.json" end

---@param root string
---@return string
function M.diagnostics_file(root) return M.watch_dir(root) .. "/diagnostics.json" end

---@param root string
---@return boolean
function M.installed(root) return vim.fn.filereadable(M.dir(root) .. "/NvimBridge.cs") == 1 end

local ASMDEF = [==[{
  "name": "NvimBridge.Editor",
  "rootNamespace": "NvimBridge",
  "references": [],
  "includePlatforms": [ "Editor" ],
  "excludePlatforms": [],
  "allowUnsafeCode": false,
  "overrideReferences": false,
  "autoReferenced": false,
  "noEngineReferences": false
}
]==]

local SCRIPT = [==[// The Neovim bridge. Generated by lua/lang/unity/bridge.lua; do not edit --
// reinstall it from <Leader>r instead, which is also how it is updated.
//
// One way, editor -> Neovim, over two files under Library/ (which Unity's own
// .gitignore already excludes):
//
//   Library/nvim-unity/state.json        the editor's live state
//   Library/nvim-unity/diagnostics.json  the last compile's messages
//
// Nothing is ever read back and no socket is opened, so there is nothing here
// that can hang the editor or interfere with a build. Every write is wrapped:
// a bridge that cannot write its state file must still never break the editor.
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Compilation;

namespace NvimBridge
{
    [InitializeOnLoad]
    internal static class Bridge
    {
        // Kept in step with `M.VERSION` in lua/lang/unity/bridge.lua.
        const int Version = 1;

        static readonly string Dir = Path.Combine(Directory.GetCurrentDirectory(), "Library", "nvim-unity");
        static readonly string StatePath = Path.Combine(Dir, "state.json");
        static readonly string DiagnosticsPath = Path.Combine(Dir, "diagnostics.json");
        static readonly int Pid = Process.GetCurrentProcess().Id;

        // Messages for the compile that is running now. Cleared when one starts
        // and flushed when it ends, so a half-finished compile never lands in
        // the file as if it were the result.
        static readonly List<CompilerMessage> pending = new List<CompilerMessage>();

        // The last payload written. Polling runs four times a second; almost
        // every tick is identical, and an unchanged file is a file Neovim is
        // not woken up for.
        static string lastState;
        static double nextPoll;

        static Bridge()
        {
            EditorApplication.playModeStateChanged += _ => WriteState();
            EditorApplication.pauseStateChanged += _ => WriteState();
            EditorApplication.update += Poll;
            EditorApplication.quitting += OnQuitting;

            CompilationPipeline.compilationStarted += _ => pending.Clear();
            CompilationPipeline.assemblyCompilationFinished += OnAssemblyFinished;
            CompilationPipeline.compilationFinished += _ => WriteDiagnostics();

            // This constructor runs again after every domain reload, so this is
            // also how the state file catches up once a reload is over.
            WriteState();
        }

        static void Poll()
        {
            var now = EditorApplication.timeSinceStartup;
            if (now < nextPoll) return;
            nextPoll = now + 0.25;
            WriteState();
        }

        // Ordered by what you would want to read if two were true at once: a
        // build outranks play mode, and play mode outranks the compile that
        // Unity defers until you leave it.
        static string CurrentState()
        {
            if (BuildPipeline.isBuildingPlayer) return "building";
            if (EditorApplication.isPaused) return "paused";
            if (EditorApplication.isPlaying) return "playing";
            if (EditorApplication.isCompiling) return "compiling";
            if (EditorApplication.isUpdating) return "importing";
            return "idle";
        }

        static void WriteState()
        {
            var sb = new StringBuilder();
            sb.Append("{\"schema\":1");
            sb.Append(",\"bridge\":").Append(Version);
            sb.Append(",\"pid\":").Append(Pid);
            sb.Append(",\"state\":").Append(Quote(CurrentState()));
            sb.Append(",\"playing\":").Append(Bool(EditorApplication.isPlaying));
            sb.Append(",\"paused\":").Append(Bool(EditorApplication.isPaused));
            sb.Append(",\"compiling\":").Append(Bool(EditorApplication.isCompiling));
            sb.Append(",\"importing\":").Append(Bool(EditorApplication.isUpdating));
            sb.Append(",\"building\":").Append(Bool(BuildPipeline.isBuildingPlayer));
            sb.Append(",\"project\":").Append(Quote(Directory.GetCurrentDirectory()));
            sb.Append('}');

            // No timestamp anywhere in there, so that this comparison means
            // "nothing changed" rather than "no time passed".
            var payload = sb.ToString();
            if (payload == lastState) return;
            lastState = payload;
            Write(StatePath, payload);
        }

        static void OnAssemblyFinished(string assembly, CompilerMessage[] messages)
        {
            foreach (var message in messages)
            {
                if (message.type == CompilerMessageType.Error || message.type == CompilerMessageType.Warning)
                    pending.Add(message);
            }
        }

        static void WriteDiagnostics()
        {
            var sb = new StringBuilder();
            sb.Append("{\"schema\":1,\"items\":[");
            for (var i = 0; i < pending.Count; i++)
            {
                var message = pending[i];
                if (i > 0) sb.Append(',');
                sb.Append("{\"file\":").Append(Quote(message.file ?? ""));
                sb.Append(",\"line\":").Append(message.line.ToString(CultureInfo.InvariantCulture));
                sb.Append(",\"column\":").Append(message.column.ToString(CultureInfo.InvariantCulture));
                sb.Append(",\"severity\":")
                  .Append(Quote(message.type == CompilerMessageType.Error ? "error" : "warning"));
                sb.Append(",\"message\":").Append(Quote(message.message ?? "")).Append('}');
            }
            sb.Append("]}");
            Write(DiagnosticsPath, sb.ToString());
        }

        // A clean quit removes the state file, which is how Neovim tells "the
        // editor closed" from "the editor is idle". A crash leaves it behind,
        // and Neovim falls back to checking whether the pid is still alive.
        static void OnQuitting()
        {
            try
            {
                if (File.Exists(StatePath)) File.Delete(StatePath);
            }
            catch (IOException) { }
        }

        // Written beside the target and moved into place, so a reader woken by
        // the change never sees half a document.
        static void Write(string path, string payload)
        {
            try
            {
                Directory.CreateDirectory(Dir);
                var temp = path + ".tmp";
                File.WriteAllText(temp, payload);
                if (File.Exists(path)) File.Delete(path);
                File.Move(temp, path);
            }
            catch (IOException) { }
        }

        static string Bool(bool value) { return value ? "true" : "false"; }

        static string Quote(string value)
        {
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < ' ') sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        else sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
]==]

--- The exclude file wants repository-relative patterns, and the Unity project
--- is not always the repository root.
---@param root string
---@return string|nil exclude_file
---@return string prefix `""`, or `"sub/dir/"`.
local function git_exclude_file(root)
  local function git(...)
    local result = vim.system({ "git", "-C", root, ... }, { text = true }):wait()
    if result.code ~= 0 then return nil end
    return vim.trim(result.stdout or "")
  end

  local git_dir = git("rev-parse", "--absolute-git-dir")
  local top = git("rev-parse", "--show-toplevel")
  if not git_dir or git_dir == "" or not top or top == "" then return nil, "" end

  local prefix = ""
  local canonical = vim.fn.resolve(vim.fn.fnamemodify(root, ":p")):gsub("/$", "")
  top = vim.fn.resolve(top):gsub("/$", "")
  if canonical ~= top then prefix = canonical:sub(#top + 2) .. "/" end

  vim.fn.mkdir(git_dir .. "/info", "p")
  return git_dir .. "/info/exclude", prefix
end

---@param root string
---@return string|nil summary A line for the install notification.
function M.hide_from_git(root)
  local path, prefix = git_exclude_file(root)
  if not path then return nil end

  local existing = vim.fn.filereadable(path) == 1 and vim.fn.readfile(path) or {}
  local present = {}
  for _, line in ipairs(existing) do
    present[vim.trim(line)] = true
  end

  local missing = {}
  for _, pattern in ipairs(EXCLUDES) do
    local entry = prefix .. pattern
    if not present[entry] then table.insert(missing, entry) end
  end
  if vim.tbl_isempty(missing) then return ("already hidden from git in %s"):format(vim.fn.fnamemodify(path, ":~")) end

  local lines = vim.deepcopy(existing)
  if not vim.tbl_isempty(lines) and vim.trim(lines[#lines]) ~= "" then table.insert(lines, "") end
  table.insert(lines, "# Neovim's Unity bridge -- local only")
  vim.list_extend(lines, missing)

  local ok = pcall(vim.fn.writefile, lines, path)
  if not ok then return ("could not write %s -- hide %s by hand"):format(path, M.FOLDER) end
  return ("hidden from git in %s (this clone only)"):format(vim.fn.fnamemodify(path, ":~"))
end

--- Safe to re-run; that is how the script is updated when `M.VERSION` moves.
---@param root? string
---@return boolean ok
function M.install(root)
  root = root or require("lang.unity.project").require_root()
  if not root then return false end

  local dir = M.dir(root)
  vim.fn.mkdir(dir, "p")

  for name, content in pairs { ["NvimBridge.cs"] = SCRIPT, ["NvimBridge.Editor.asmdef"] = ASMDEF } do
    local file, err = io.open(dir .. "/" .. name, "w")
    if not file then
      vim.notify(("Could not write %s/%s: %s"):format(dir, name, err), vim.log.levels.ERROR, { title = "Unity" })
      return false
    end
    file:write(content)
    file:close()
  end

  local hidden = M.hide_from_git(root)
  vim.notify(
    ("Bridge installed in %s\n  %s\n\nUnity compiles it the next time it has focus, and state is reported from then on."):format(
      M.FOLDER,
      hidden or "not a git repository, so nothing to hide"
    ),
    vim.log.levels.INFO,
    { title = "Unity" }
  )

  require("lang.unity.state").start(root)
  return true
end

--- The `.git/info/exclude` lines are left alone: they are harmless, and
--- removing them is the one part of this that can lose somebody else's line.
---@param root? string
function M.uninstall(root)
  root = root or require("lang.unity.project").require_root()
  if not root then return end

  if not M.installed(root) then
    vim.notify("No bridge installed in this project", vim.log.levels.INFO, { title = "Unity" })
    return
  end

  vim.fn.delete(root .. "/" .. M.FOLDER, "rf")
  vim.fn.delete(root .. "/" .. M.FOLDER .. ".meta")
  vim.fn.delete(M.watch_dir(root), "rf")
  require("lang.unity.state").stop()
  require("lang.unity.diagnostics").clear()

  vim.notify(
    ("Bridge removed from %s.\nThe .git/info/exclude lines were left in place."):format(M.FOLDER),
    vim.log.levels.INFO,
    { title = "Unity" }
  )
end

return M
