local M = {}

--- Roots this session has already tried to claim the socket for; the point is
--- that a second attempt is never made.
---@type table<string, boolean>
local registered = {}

--- Not on `$PATH` on purpose: nothing should pick this up by accident, and
--- Unity is given the absolute path.
M.path = vim.fn.expand "~/.local/share/nvim-unity/bin/code"

---@param root string
---@return string
function M.socket_path(root)
  local dir = (vim.env.XDG_RUNTIME_DIR or "/tmp") .. "/nvim-unity"
  vim.fn.mkdir(dir, "p")
  return ("%s/%s.sock"):format(dir, vim.fn.sha256(root):sub(1, 16))
end

---@param payload string
---@return integer
local function open(payload)
  local decoded = vim.base64.decode(payload)
  local path, line, column = unpack(vim.split(decoded, "\t", { plain = true }))
  if not path or path == "" then return 0 end

  vim.schedule(function()
    vim.cmd.edit(vim.fn.fnameescape(path))
    local row = math.max(1, tonumber(line) or 1)
    local col = math.max(0, (tonumber(column) or 1) - 1)
    vim.api.nvim_win_set_cursor(0, { math.min(row, vim.api.nvim_buf_line_count(0)), col })
    vim.cmd "normal! zz"
    -- Unity is the foreground window when you double-click a script, so say
    -- something: the file changed under a terminal you were not looking at.
    vim.notify(("Opened %s:%d from Unity"):format(vim.fs.basename(path), row), vim.log.levels.INFO, { title = "Unity" })
  end)
  return 1
end

---@param root string
---@return boolean listening
function M.register(root)
  if registered[root] ~= nil then return registered[root] end

  -- The shim reaches this through `--remote-expr v:lua.UnityOpenFromEditor`,
  -- which can only call a global.
  _G.UnityOpenFromEditor = open

  local path = M.socket_path(root)

  -- A socket left behind by a Neovim that was killed rather than quit. Probing
  -- is the only way to tell that from a live one; `sockconnect` throws on a
  -- dead socket, which is the answer we want.
  if vim.uv.fs_stat(path) then
    local ok, channel = pcall(vim.fn.sockconnect, "pipe", path, { rpc = true })
    if ok and channel ~= 0 then
      pcall(vim.fn.chanclose, channel)
      registered[root] = false
      return false
    end
    vim.fn.delete(path)
  end

  local ok = pcall(vim.fn.serverstart, path)
  registered[root] = ok
  return ok
end

---@param root string
---@return boolean
function M.listening(root) return vim.uv.fs_stat(M.socket_path(root)) ~= nil end

local SCRIPT = [==[#!/usr/bin/env bash
# Unity's "Visual Studio Code", which is actually Neovim.
#
# Generated by lua/lang/unity/shim.lua; do not edit -- reinstall it from
# <Leader>r instead.
#
# Unity calls this as:
#     code "<project dir>"
#     code "<project dir>" -g "<file>":<line>:<column>
set -uo pipefail

project="${1:-}"
target=""
while [ $# -gt 0 ]; do
  if [ "$1" = "-g" ]; then
    shift
    target="${1:-}"
    break
  fi
  shift
done

runtime="${XDG_RUNTIME_DIR:-/tmp}/nvim-unity"
key=$(printf '%s' "$project" | sha256sum | cut -c1-16)
sock="$runtime/$key.sock"

if [ -n "$target" ] && [ -S "$sock" ]; then
  # "path:line:column", but a path can contain colons, so peel from the right.
  rest="${target##*:}"; head="${target%:*}"
  col="$rest"; line="${head##*:}"; file="${head%:*}"
  case "$col$line" in
    *[!0-9]*) file="$target"; line=1; col=1 ;;
  esac
  payload=$(printf '%s\t%s\t%s' "$file" "$line" "$col" | base64 -w0)
  if nvim --server "$sock" --remote-expr "v:lua.UnityOpenFromEditor('$payload')" >/dev/null 2>&1; then
    exit 0
  fi
fi

# No Neovim has this project open (or it stopped answering).
if [ -n "${UNITY_NVIM_TERMINAL:-}" ]; then
  cd "$project" 2>/dev/null || true
  if [ -n "$target" ]; then
    exec $UNITY_NVIM_TERMINAL nvim "+normal! ${target#*:}gg" "${target%%:*}"
  fi
  exec $UNITY_NVIM_TERMINAL nvim .
fi

message="No Neovim is listening for $(basename "$project"). Open the project in Neovim first."
command -v notify-send >/dev/null 2>&1 && notify-send "Unity -> Neovim" "$message"
echo "$message" >&2
exit 0
]==]

--- Safe to re-run; overwrites in place.
---@return boolean ok
function M.install()
  vim.fn.mkdir(vim.fs.dirname(M.path), "p")
  local fd, err = io.open(M.path, "w")
  if not fd then
    vim.notify(("Could not write %s: %s"):format(M.path, err), vim.log.levels.ERROR, { title = "Unity" })
    return false
  end
  fd:write(SCRIPT)
  fd:close()
  vim.uv.fs_chmod(M.path, 493)

  vim.notify(
    ("Shim installed at %s\n\nIn Unity: Edit > Preferences > External Tools >\n  External Script Editor > Browse... > that path.\n\nUnity then treats it as Visual Studio Code: it binds its control\nsocket (play, pause, refresh, tests) and regenerates SDK-style\ncsproj files with the Unity analyzers attached."):format(
      M.path
    ),
    vim.log.levels.INFO,
    { title = "Unity" }
  )
  return true
end

return M
